### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by PrateekRS12** [anthonysirico/IC-GSBD#3]
Im a college student and two of us are working on the research topic you have worked on so we wanted to know about the dataset you have used ? How to contact you ?

**Comment by anthonysirico** [comment]
You can contact me here or you can email me at anthony.sirico@colostate.edu. If you would prefer I can put you touch with the sets creator.

**Comment by Sarpabhushanangadi** [comment]
surely we will connect you on email sir. Thank you for the reply sir .

**Comment by Sarpabhushanangadi** [comment]
Sir , we are expecting the response from you through the mail, So please help us accordingly. Thank you sir .

**Comment by anthonysirico** [comment]
Closed
